# Dockerfile for the Free Tier Flask application.
#
# This Dockerfile builds a minimal container image for running the Flask API
# that launches Kubernetes jobs. It installs the required dependencies and
# copies the application code into the image. 
# Students may modify this file to add build steps or change the base image as needed.


# TODO: Specify a Python base image
FROM python:3.6

# TODO: Set the working directory
WORKDIR /app/

# TODO: Copy the necessary application files into the image (from free_service/app/ directory)
COPY mp12_microarch_twotier_starter/free_service/app/ /app/

# TODO: Install Python dependencies
RUN pip3 install --upgrade pip
RUN pip3 install -r /app/requirements_flaskapp.txt 

# TODO: Expose the required port
EXPOSE 5000

# Specify the default command to run the Flask app
CMD ["python3", "/app/flask_app.py"]
