#
# This YAML defines a template for launching a batch job in the 'free-service' namespace.
# The job runs a container that performs a classification task.
#
# TODO: Fill in the Kubernetes Job spec here.
apiVersion: batch/v1
kind: Job
metadata:
  name: free-tier-job
  namespace: free-service
spec:
  template:
    metadata:
      labels:
        dataset: mnist
    spec:
      containers:
        - name: free-tier-job # names don't need to match
          image: amyyuan2244/free-tier-job-docker:latest  # TODO: swap?
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 4