# Starter Dockerfile for the web-tier Envoy proxy.
#
# This Dockerfile should package Envoy with a custom configuration for the web tier.
# Students should complete the steps below as needed for their assignment.
#

# TODO: Specify the Envoy base image
FROM envoyproxy/envoy:v1.22.0
# https://www.envoyproxy.io/docs/envoy/v1.38.0/start/docker TODO: which version?

# TODO: Copy the Envoy configuration file into the image
COPY /mp12_microarch_twotier_starter/web_tier/web_tier_envoy.yaml /etc/envoy/envoy.yaml

# TODO: Expose the required ports
EXPOSE 8080

# TODO: Specify the default command to run Envoy
CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]