# Starter Dockerfile for the Premium Tier job container.
#
# This Dockerfile builds a container image for running classification jobs
# in the 'premium-service' namespace. It installs dependencies, preloads data,
# and pretrains models. 
# Students may modify this file to change the job behavior or add new dependencies.


# Specify the base image
FROM python:3.6

# DATASET: Specifies the dataset (mnist or kmnist).
# TYPE: Specifies the model type (ff for feed-forward or cnn for convolutional neural network).
# Premium-service configuration: cnn, kmnist

ENV DATASET="kmnist"
ENV TYPE="cnn"

# TODO: Set the working directory
WORKDIR /app/

# Copy model and source files into the image (from /mp12_microarch_twotier_starter/model_config/ directory)
COPY mp12_microarch_twotier_starter/model_config/requirements.txt /app/
COPY mp12_microarch_twotier_starter/model_config/classify.py /app/
COPY mp12_microarch_twotier_starter/model_config/data_preload.py /app/
COPY mp12_microarch_twotier_starter/model_config/train.py /app/
COPY mp12_microarch_twotier_starter/model_config/utils.py /app/
COPY mp12_microarch_twotier_starter/model_config/models.py /app/

# TODO: Install Python dependencies
RUN pip3 install --upgrade pip
# numpy, torch, torchvision
RUN pip3 install -r /app/requirements.txt 

# TODO: Create directories for models and data
RUN mkdir -p ./models
RUN mkdir -p /app/data/KMNIST/raw

COPY mp12_microarch_twotier_starter/data/MNIST/raw/ /app/data/MNIST/raw/
COPY mp12_microarch_twotier_starter/data/KMNIST/raw/ /app/data/KMNIST/raw/

# TODO: Preload data and pretrain models
RUN python3 /app/data_preload.py
RUN python3 /app/train.py

# TODO: Expose the required port
EXPOSE 5000

# TODO: Specify the default command to run the classification script
CMD ["python", "/app/classify.py"]